services:
  prometheus:
    image: prom/prometheus:v3.6.0
    ports:
      - "9090:9090"
    networks:
      - shared_ecommerce_network
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.dev.yml

  grafana:
    image: grafana/grafana:12.3.0-18147126998
    ports:
      - "3000:3000"
    networks:
      - shared_ecommerce_network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards/json:/var/lib/grafana/dashboards

networks:
  shared_ecommerce_network:
    external: true