services:
  prometheus:
    image: wesley00s/prometheus-ecommerce:latest
    ports:
      - "9090:9090"
    networks:
      - shared_ecommerce_network
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: wesley00s/grafana-ecommerce:latest
    ports:
      - "3000:3000"
    networks:
      - shared_ecommerce_network
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  shared_ecommerce_network:
    external: true

volumes:
  prometheus_data:
  grafana_data: