global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'ecommerce-app'
    metrics_path: /ecommerce/api/actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['${ECOMMERCE_HOST}:443']

  - job_name: 'reviews-app'
    metrics_path: /reviews/api/actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['${REVIEWS_HOST}:443']

  - job_name: 'payment-app'
    metrics_path: /payment/api/actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['${PAYMENT_HOST}:443']