global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'ecommerce-app'
    metrics_path: /ecommerce/api/actuator/prometheus
    static_configs:
      - targets: ['ecommerce-app:8080']

  - job_name: 'reviews-app'
    metrics_path: /reviews/api/actuator/prometheus
    static_configs:
      - targets: ['reviews-app:8081']

  - job_name: 'payment-app'
    metrics_path: /payment/api/actuator/prometheus
    static_configs:
      - targets: ['payment-app:8082']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']