name: Monitoring Stack CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  PROM_IMAGE: wesley00s/prometheus-ecommerce
  GRAF_IMAGE: wesley00s/grafana-ecommerce

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Prometheus
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prometheus
          
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.PROM_IMAGE }}:${{ github.sha }}
            ${{ env.PROM_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Grafana
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.grafana
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GRAF_IMAGE }}:${{ github.sha }}
            ${{ env.GRAF_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max